language: java

jdk:
  - oraclejdk8

script:
  - cd master
  - ./gradlew build
  - ./gradlew test
  - ./gradlew integrationTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/